#!usr/bin/python3
import discord
import json
import nmap
import asyncio

def flatten_dict(dd, separator='_', prefix=''):
    return { prefix + separator + k if prefix else k : v
             for kk, vv in dd.items()
             for k, v in flatten_dict(vv, separator, kk).items()
             } if isinstance(dd, dict) else { prefix : dd }

nm = nmap.PortScanner()

class AlertBot(discord.Client):
    def __init__(self, mac, channel_id, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.bg_task = self.loop.create_task(self.send_alert())
        self.mac = mac
        self.channel_id = channel_id

    async def on_ready(self):
        print(f'{self.user} is now connected to {self.guilds[0]}')

    async def send_alert(self):
        await self.wait_until_ready()
        at_home = False
        scan = nm.scan('192.168.1.0/24', arguments='-n -sP -PE -T5')
        channel = self.get_channel(self.channel_id)
        while not self.is_closed():
            if (not at_home) and (self.mac in flatten_dict(scan).values()):
                await channel.send('UH OH')
                at_home = True
            if (self.mac not in flatten_dict(scan).values()):
                at_home = False
            await asyncio.sleep(120)

if __name__ == "__main__":
    conf = json.load(open('config.json'))
    client = AlertBot(conf['mac'], conf['channel_id'])
    client.run(conf['TOKEN'])
